# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'objective_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wyzepro

  target 'objective_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'objective_appUITests' do
    # Pods for testing
  end

  pod 'FLEX'
  pod 'AFNetworking' , '4.0.1'
  pod 'Masonry', '1.1.0'
  pod 'FLAnimatedImage',' 1.0.12'
  pod 'FMDB', '2.7.5'
  pod 'IQKeyboardManager', '6.3.0'
  pod 'JSONModel', '1.8.0'
#  pod 'MBProgressHUD', '0.8’
  pod 'MBProgressHUD'
  pod 'MJExtension', '3.2.1'
  pod 'MJRefresh', '3.4.3'
#  pod 'SDWebImage', '5.6.1'
  pod 'SDWebImage'
  pod 'XCDYouTubeKit', '2.8.1'
  pod 'SSZipArchive', '2.2.3'
  pod 'pop', '1.0.12'
  pod 'CocoaAsyncSocket', '7.6.4'
  pod 'AvoidCrash', '2.5.2'
  pod 'ZZCircleProgress', '0.0.2'
  pod 'RealReachability', '1.3.0'
  pod 'FSCalendar', '2.7.9'
  pod 'xxtea', '1.0.1'
  pod 'YYText', '1.0.7'
  pod 'lottie-ios', '2.5.3'
  pod 'Firebase', '6.26.0'
  pod 'FirebaseMessaging', '4.1.5'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Analytics', '3.7.1'
  #    pod 'Firebase/Analytics'
  pod 'Appboy-iOS-SDK/Core', '3.21.3'
  pod 'Appboy-iOS-SDK/InAppMessage'
  pod 'Segment-Appboy', '3.0.0'
  pod 'DZNEmptyDataSet'
  pod "UIAlertView-Blocks", "~> 1.0"
  
end
